config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/about', to:"pages#about"
  get '/help', to:"pages#help"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :tbls
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tbl.rb
class Tbl<ApplicationRecord
    validates :name,presence: true
    validates :description,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def hello
  render plain:"Hello!!"
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

  def help

  end

end

app/controllers/tbls_controller.rb
class TblsController <ApplicationController

  before_action :set_todo,only: [:edit, :update, :show, :destory]

  def new
    @todo=Tbl.new
  end

  def create
    @todo=Tbl.new(tbl_params)
    if @todo.save
      flash[:notice]="Todo is created"
      redirect_to tbl_path(@todo)
    else
      render 'new', status: 422
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update(tbl_params)
      flash[:notice]="Todo is Updated Successfully"
      redirect_to tbl_path(@todo)
    else
      render 'edit', status: 422
    end
  end

  def index
    @todo=Tbl.all
  end

  def destroy
    @todo.destroy
    redirect_to tbl_path(), status: :see_other
  end

  private

  def set_todo
    @todo = Tbl.find(params[:id])
  end
  def tbl_params
    params.require(:tbl).permit(:name,:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
 <%flash.each do |name,msg|%>
    <ul>
        <li><%=msg%></li>
    </ul>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hello About</h1>

app/views/pages/help.html.erb
<a href="https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.pixabay.com%2Fphoto%2F2014%2F02%2F27%2F16%2F10%2Fflowers-276014__340.jpg&imgrefurl=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fnature%2F&tbnid=kFu7-YLw-41T3M&vet=12ahUKEwjXvs-Dp-f8AhXATqQEHQWIADMQMygAegUIARDcAQ..i&docid=Ba_eiczVaD9-zM&w=534&h=340&itg=1&q=nature%20pics&client=ubuntu&ved=2ahUKEwjXvs-Dp-f8AhXATqQEHQWIADMQMygAegUIARDcAQ">Image Link</a>

app/views/pages/home.html.erb
<h1>
    Hello World!!!
</h1>

app/views/tbls/_form.html.erb
<% if @todo.errors.any?%>
	<h3>
		Following are the error that are occuring due to Incorrect Params
	</h3>

	<ul>
		<% @todo.errors.full_messages.each do |msg|%>
			<li><%=msg%></li>
		<%end%>
  </ul>
<%end%>

<%= form_for @todo do |f| %>
    <p>
        <%= f.label :name, "Name" %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :description, "Description" %> <br>
        <%= f.text_area  :description %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<%end%>
<%= link_to "Back to Todo Listing", tbls_path() %>

app/views/tbls/destroy.html.erb
<h1>Hi<h1>

app/views/tbls/edit.html.erb
<h1>
  Editing Data in Table
</h1>
<%= render "form"%>

app/views/tbls/index.html.erb
<h3>List of All Todos</h3>
<p>
    <%= link_to "Create a Todo" , new_tbl_path %>
</p>
<% if @todo%>
    <table>
        <tr>
            <th>Name</th>
            <th>Description</th>
        </tr>
        <% @todo.each do |todo|%>
            <tr>
                <td><%= todo.name%></td>
                <td><%= todo.description %></td>
                <td><%= link_to "Edit", edit_tbl_path(todo) %></td>
                <td><%= link_to "Show", tbl_path(todo) %></td>
                <td><%= link_to "Destroy", tbl_path(todo), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>
            </tr>
        <% end %>
    </table>
<% else %>
    <h4>
        Nothing to display!!!
    <h4>
<% end %>

app/views/tbls/new.html.erb
<h1>Create New Table</h1>
<% if @todo.errors.any?%>
    <h3>Following are the error that are occuring due to Incorrect Params</h3>
    <ul>
    <% @todo.errors.full_messages.each do |msg|%>
    <li><%=msg%></li>
    <%end%>
    </ul>
<%end%>
<%= form_for @todo do |f|%>
    <p>
        <%= f.label :name, "Name" %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :description, "Description"%> <br>
        <%= f.text_area  :description%>
    </p>

    <p>
        <%= f.submit "Submit"%>
    </p>
<%end%>
<%= link_to "Back to Todo Listing", tbls_path() %>

app/views/tbls/show.html.erb
<h4>
  <% if @tblid %>
    <p>
      Name: <%=@tblid.name%>
    </p>
    <p>
      Description: <%=@tblid.description%>
    </p>
  <% end %>
</h4>
<%= link_to "Edit", edit_tbl_path(@tblid) %> |
<%= link_to "Back to Todo Listing", tbls_path() %>